#!/bin/bash
echo "."
echo "."
echo "."
echo "."
echo ".........   PLease wait while we setup K8S Play ground......"
echo "."
echo "."
echo "."
echo "."
apt update && apt upgrade -y
apt install curl apt-transport-https vim git wget software-properties-common lsb-release ca-certificates -y
swapoff -a
modprobe overlay
modprobe br_netfilter
cat << EOF | tee /etc/sysctl.d/kubernetes.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF
sysctl --system
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
usermod -aG sudo ninja01
usermod -aG docker ninja01
apt-get update && apt-get install containerd.io -y
containerd config default | tee /etc/containerd/config.toml
sed -e 's/SystemdCgroup = false/SystemdCgroup = true/g' -i /etc/containerd/config.toml
systemctl restart containerd
echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main' >/etc/apt/sources.list.d/kubernetes.list
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add
apt-get update
apt-get install -y kubeadm=1.27.1-00 kubelet=1.27.1-00 kubectl=1.27.1-00 -y
apt-mark hold kubelet kubeadm kubectl
kubeadm init --config=kubeadm-config.yaml --upload-certs | tee kubeadm-init.out
exit
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
sleep 2
echo "                                                            "
echo "                                                            "  
echo "               $$$$$$$$  $$$$$$$$$$                         "
echo "                                                            "
echo "                                                            "
echo "____________________________________________________________"
sleep 2
echo "$$$$$$$$  Ninja01 k8s Automated Spin up Complete! $$$$$$$$$$"
echo "                                                            "
echo "                                                            "  
echo "               $$$$$$$$  $$$$$$$$$$                         "
echo "                                                            "
echo "                                                            "
echo "____________________________________________________________"
echo "Let the K8S Games Begin! Happy kubectling......LOl!........."
